### ISSUE TITLE
Using Bunyan "plugins"

### ISSUE THREAD

**Issue by dainbrump** [eropple/nestjs-bunyan#5]
Is it possible to use this with Bunyan extensions such as [bunyan-cloudwatch](https://github.com/mirkokiefer/bunyan-cloudwatch)?

**Comment by Destreyf** [comment]
@dainbrump 

You should be able to, i am using the file stream plugin, my ROOT_LOGGER looks like this:
```typescript
import { Bunyan } from '@eropple/nestjs-bunyan';

export const ROOT_LOGGER = Bunyan.createLogger({
  name: 'API',
  level: Bunyan.TRACE,
  streams: [{
    path: '/var/log/api.log'
  }]
});
```

so in theory you could use it like by doing something like this:
```typescript
import { Bunyan } from '@eropple/nestjs-bunyan';
import * as createCWStream from 'bunyan-cloudwatch';

var stream = createCWStream({
  logGroupName: 'my-group',
  logStreamName: 'my-stream',
  cloudWatchLogsOptions: {
    region: 'us-west-1'
  }
});

export const ROOT_LOGGER = Bunyan.createLogger({
  name: 'API',
  level: Bunyan.TRACE,
  streams: [{
     stream: stream,
     type: 'raw'
  }]
});
```

I don't use CloudWatch so i don't know for sure if that's the way to set up the individual plugin, but the stream should work without issue.

**Comment by dainbrump** [comment]
@Destreyf Perfect. I was most of the way there. Your example pushed it over the edge. Works like a champ now. Thanks.
